### ISSUE TITLE
ActiveSupport requirement for caching support

### ISSUE THREAD

**Issue by hectorcorrea** [ebsco/edsapi-ruby#56]
It would be nice if this gem did not require 5.x version of ActiveSupport https://github.com/ebsco/edsapi-ruby/blob/master/ebsco-eds.gemspec#L46

We are still using Rails 4.x. 

It would be even nicer if the gem did not depend on Rails components at all but that might be heresy :)

**Comment by bmckinney** [comment]
Good point! The dependency is really only needed for the default cache store for the faraday caching middleware (when caching is turned on). See: https://github.com/ebsco/edsapi-ruby/blob/6b1d455d0cca6556965f4b58684fbf6124c9c4ab/lib/ebsco/eds/session.rb#L131-L135

Maybe we can find a non-activesupport cache store default? 

In any case, the long-term plan is to make this configurable since non-filestore cache stores are probably the way to go in a production environment. You will probably want to enable caching to avoid duplicate and unnecessary API calls.

**Comment by bmckinney** [comment]
Also, I'll test against a 4.x version and see if there is any reason we really need 5.x for the caching dependency.

**Comment by JPrevost** [comment]
Is there any progress on providing non-filestore cache options? My preference is to default to my Rails app configured cache.

**Comment by sandbergja** [comment]
In the opposite direction from Hector, I'm trying to upgrade my app to Rails 6, but the ActiveSupport version is getting in the way.

**Comment by efrierson** [comment]
We attempted to use Rails 4, but looks like our caching is incompatable with that.  Many thanks @sandbergja for helping loosen up the depenencies for support for later versions of Rails (tested up to 6.1) and its activesupport module.
